services:
  app:
    image: chargeback-front
    container_name: chargeback-front
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ENV=${NODE_ENV:-}
    restart: unless-stopped
    ports:
      - "${NODE_PORT:-3000}:3000"
    environment:
      - API_BASE_URL_INTERNAL=http://laravel:80
      - NEXTAUTH_SECRET=DA7yaoTFT5Gl5czkmkT34FLvFtPqcRm05NVkYqTJPQE=
      - NEXTAUTH_URL=http://localhost:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - backend

networks:
  backend:
    external: true
    name: backend_sail
